'use strict';

const { send, cors, page, query, gemini, clampNumber, cleanText, rootDomain } = require('../api-lib');

async function publicRank(hostname){
  if(!process.env.OPENPAGERANK_API_KEY)return null;
  try{const domain=rootDomain(hostname);const r=await fetch(`https://openpagerank.com/api/v1.0/getPageRank?domains[]=${encodeURIComponent(domain)}`,{headers:{'API-OPR':process.env.OPENPAGERANK_API_KEY},signal:AbortSignal.timeout(9000)});const j=await r.json();return r.ok?j.response?.[0]||null:null;}catch{return null;}
}
function list(value,max=15){return Array.isArray(value)?value.map((x)=>({status:['pass','warn','info'].includes(x?.status)?x.status:'info',title:cleanText(x?.title),detail:cleanText(x?.detail),action:cleanText(x?.action)})).filter((x)=>x.title||x.detail).slice(0,max):[];}
module.exports=async function visibility(req,res){
  if(cors(req,res))return;if(req.method!=='GET')return send(res,405,{message:'Method not allowed.'});
  try{
    const input=query(req),website=await page(input.url),rank=await publicRank(new URL(website.finalUrl).hostname);
    const result=await gemini(`Create a transparent public organic search visibility assessment. This is NOT a traffic report and must not claim verified rankings, Search Console data, exact monthly visits, backlink counts or proprietary domain rating. Use public webpage evidence and the supplied public authority metric only.\n\nURL:${website.finalUrl}\nKeyword:${input.keyword||''}\nCountry:${input.country||'Pakistan'}\nCity:${input.city||''}\nHTTP:${website.status}\nResponse:${website.ms}ms\nTitle:${website.title}\nDescription:${website.description}\nH1:${website.h1.join(' | ')}\nWords:${website.wordCount}\nCanonical:${website.canonical}\nRobots:${website.robots}\nSchema:${website.schemaTypes.join(', ')}\nOpenPageRank:${rank?.page_rank_decimal??'Unavailable'}\n\nReturn {"searchReadinessScore":0-100,"visibilityLevel":"Very limited|Limited|Developing|Established|Strong","confidence":"Low|Medium","indexabilitySignal":"","contentCoverage":"","authoritySignal":"","localSignal":"","strengths":[{"status":"pass","title":"","detail":"","action":""}],"gaps":[{"status":"warn","title":"","detail":"","action":""}],"opportunities":[{"status":"info","title":"","detail":"","action":""}],"signalScores":{"indexability":0-100,"contentCoverage":0-100,"authority":0-100,"localRelevance":0-100,"aiAnswerReadiness":0-100}}.`);
    return send(res,200,{sourceLabel:'AI-assisted public organic visibility assessment',dataType:'Public signals — not verified Google data',disclaimer:'This report evaluates public search-readiness signals. It does not claim exact rankings, traffic or Search Console performance.',site:{name:website.siteName,url:website.finalUrl,favicon:website.favicon,title:website.title},searchReadinessScore:clampNumber(result.searchReadinessScore,0,100,50),visibilityLevel:cleanText(result.visibilityLevel,'Developing'),confidence:String(result.confidence).toLowerCase()==='medium'?'Medium':'Low',indexabilitySignal:cleanText(result.indexabilitySignal,'Not enough evidence'),contentCoverage:cleanText(result.contentCoverage,'Not enough evidence'),authoritySignal:cleanText(result.authoritySignal,rank?`OpenPageRank ${rank.page_rank_decimal}`:'Unverified'),localSignal:cleanText(result.localSignal,'Not assessed'),strengths:list(result.strengths),gaps:list(result.gaps),opportunities:list(result.opportunities),publicAuthority:rank?{source:'OpenPageRank',value:rank.page_rank_decimal,rank:rank.rank}:null,signalScores:{indexability:clampNumber(result.signalScores?.indexability,0,100,50),contentCoverage:clampNumber(result.signalScores?.contentCoverage,0,100,50),authority:clampNumber(result.signalScores?.authority,0,100,rank?Math.min(100,Math.round(Number(rank.page_rank_decimal||0)*20)):35),localRelevance:clampNumber(result.signalScores?.localRelevance,0,100,40),aiAnswerReadiness:clampNumber(result.signalScores?.aiAnswerReadiness,0,100,35)}});
  }catch(error){return send(res,400,{message:error.message});}
};
